name: SonarQube Code Analysis

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  sonarqube:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 9.4.0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Tests with Coverage
        run: pnpm test -- --coverage

      - name: Check code structure
        run: |
          echo "Checking project structure:"
          ls -la
          echo "src directory:"
          ls -la src || echo "src directory not found"
          echo "tests directory:"
          ls -la tests || echo "tests directory not found"
          echo "coverage directory:"
          ls -la coverage || echo "coverage directory not found"

      - name: Debug SonarQube config
        run: cat sonar-project.properties

      # 主分支扫描配置
      - name: SonarQube Scan (main branch)
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=code-cracks_code-crack
            -Dsonar.organization=code-cracks 
            -Dsonar.branch.name=main

      # PR扫描配置(禁用)
      - name: SonarQube Scan (regular branch)
        if: github.event_name == 'pull_request'
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=code-cracks_code-crack
            -Dsonar.organization=code-cracks
            -Dsonar.scm.provider=git
            -Dsonar.sources=src
            -Dsonar.branch.name=${{ github.head_ref || github.ref_name }}
